import{a as q,S as M,i as p}from"./assets/vendor-Bt_EzQve.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const h=15,E="53049514-dee19204cd3e9e15730e86423",$=q.create({baseURL:"https://pixabay.com/api/",params:{key:E,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h}});async function g(e,o=1){const{data:i}=await $.get("",{params:{q:e,page:o}});return i}const m=document.querySelector("#gallery"),L=document.querySelector("#loader");let P=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(e){const o=e.map(_).join("");m.insertAdjacentHTML("beforeend",o),P.refresh()}function A(){m.innerHTML=""}function w(){L.classList.remove("hidden")}function S(){L.classList.add("hidden")}function d(e){p.info({message:e,position:"topRight"})}function O(e){p.success({message:e,position:"topRight"})}function f(e){p.error({message:e,position:"topRight"})}function R(){const e=m.firstElementChild;if(!e)return;const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function _({webformatURL:e,largeImageURL:o,tags:i,likes:l,views:t,comments:r,downloads:s}){return`
<li class="photo-card">
  <a href="${o}" class="gallery__link">
    <img src="${e}" alt="${i}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${l}</p>
    <p><b>Views</b> ${t}</p>
    <p><b>Comments</b> ${r}</p>
    <p><b>Downloads</b> ${s}</p>
  </div>
</li>`}const c={form:document.querySelector("#search-form"),input:document.querySelector('#search-form [name="query"]'),gallery:document.querySelector("#gallery"),loadMore:document.querySelector("#load-more")};function v(){c.loadMore.classList.remove("hidden")}function y(){c.loadMore.classList.add("hidden")}let u="",a=1,n=0;y();c.form.addEventListener("submit",B);c.loadMore.addEventListener("click",H);async function B(e){if(e.preventDefault(),u=c.input.value.trim(),!u){d("Enter a search term");return}a=1,n=0,A(),y(),w();try{const o=await g(u,a);if(n=o.totalHits??0,!n){f("Sorry, no images match your search query.");return}b(o.hits),O(`Hooray! We found ${n} images.`),a*h<n?v():d("We're sorry, but you've reached the end of search results.")}catch(o){f(o.message||"Something went wrong, try again later.")}finally{S()}}async function H(){a+=1,y(),w();try{const e=await g(u,a);b(e.hits),a*h>=n?d("We're sorry, but you've reached the end of search results."):v(),R()}catch(e){f(e.message||"Something went wrong, try again later.")}finally{S()}}
//# sourceMappingURL=index.js.map
