import{a as E,S as M,i as d}from"./assets/vendor-Bt_EzQve.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const f=15,$="53049514-dee19204cd3e9e15730e86423",P=E.create({baseURL:"https://pixabay.com/api/",params:{key:$,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f}});async function m(e,o=1){const{data:a}=await P.get("",{params:{q:e,page:o}});return a}const p=document.querySelector("#gallery"),y=document.querySelector("#loader"),g=document.querySelector("#load-more");let A=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(e){const o=e.map(_).join("");p.insertAdjacentHTML("beforeend",o),A.refresh()}function B(){p.innerHTML=""}function L(){y.classList.remove("hidden")}function w(){y.classList.add("hidden")}function S(){g.hidden=!1}function q(){g.hidden=!0}function v(e){d.info({message:e,position:"topRight"})}function O(e){d.success({message:e,position:"topRight"})}function u(e){d.error({message:e,position:"topRight"})}function R(){const e=p.firstElementChild;if(!e)return;const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}function _({webformatURL:e,largeImageURL:o,tags:a,likes:c,views:t,comments:r,downloads:s}){return`
<li class="photo-card">
  <a href="${o}" class="gallery__link">
    <img src="${e}" alt="${a}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${c}</p>
    <p><b>Views</b> ${t}</p>
    <p><b>Comments</b> ${r}</p>
    <p><b>Downloads</b> ${s}</p>
  </div>
</li>`}const h={form:document.querySelector("#search-form"),input:document.querySelector('#search-form [name="query"]'),loadMore:document.querySelector("#load-more")};let l="",i=1,n=0;h.form.addEventListener("submit",H);h.loadMore.addEventListener("click",x);async function H(e){if(e.preventDefault(),l=h.input.value.trim(),!l){v("Enter a search term");return}i=1,n=0,B(),q(),L();try{const o=await m(l,i);if(n=o.totalHits,!n){u("Sorry, no images match your search query.");return}b(o.hits),O(`Hooray! We found ${n} images.`),i*f<n&&S()}catch(o){console.error(o),u("Something went wrong, try again later.")}finally{w()}}async function x(){i+=1,q(),L();try{const e=await m(l,i);b(e.hits),i*f>=n?v("We're sorry, but you've reached the end of search results."):S(),R()}catch(e){console.error(e),u("Something went wrong, try again later.")}finally{w()}}
//# sourceMappingURL=index.js.map
