import{a as q,S as A,i as m}from"./assets/vendor-Bt_EzQve.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const h=15,M="53049514-dee19204cd3e9e15730e86423",E=q.create({baseURL:"https://pixabay.com/api/",params:{key:M,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h}});async function b(e,r=1){const{data:i}=await E.get("",{params:{q:e,page:r}});return i}const y=document.querySelector("#gallery"),d=document.querySelector("#loader");document.querySelector("#load-more");let $=new A(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function L(e){const r=e.map(R).join("");y.insertAdjacentHTML("beforeend",r),$.refresh()}function P(){y.innerHTML=""}function w(){d.classList.add("is-visible"),d.hidden=!1}function S(){d.classList.remove("is-visible"),d.hidden=!0}function f(e){m.info({message:e,position:"topRight"})}function H(e){m.success({message:e,position:"topRight"})}function p(e){m.error({message:e,position:"topRight"})}function O(){const e=y.firstElementChild;if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}function R({webformatURL:e,largeImageURL:r,tags:i,likes:l,views:t,comments:o,downloads:s}){return`
<li class="photo-card">
  <a class="gallery__link" href="${r}">
    <img src="${e}" alt="${_(i)}" loading="lazy" />
  </a>
  <div class="info">
    <p><b>Likes</b> ${l}</p>
    <p><b>Views</b> ${t}</p>
    <p><b>Comments</b> ${o}</p>
    <p><b>Downloads</b> ${s}</p>
  </div>
</li>`}function _(e=""){return String(e).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}const c={form:document.querySelector("#search-form"),input:document.querySelector('#search-form [name="query"]'),gallery:document.querySelector("#gallery"),loadMore:document.querySelector("#load-more")};let u="",a=1,n=0;g();c.form.addEventListener("submit",B);c.loadMore.addEventListener("click",x);function v(){c.loadMore.hidden=!1}function g(){c.loadMore.hidden=!0}async function B(e){if(e.preventDefault(),u=c.input.value.trim(),!u){f("Enter a search term");return}a=1,n=0,P(),g(),w();try{const r=await b(u,a);if(n=r.totalHits??0,!n){p("Sorry, no images match your search query.");return}L(r.hits),H(`Hooray! We found ${n} images.`),a*h<n?v():f("We're sorry, but you've reached the end of search results.")}catch(r){p(r.message||"Something went wrong, try again later.")}finally{S()}}async function x(){a+=1,g(),w();try{const e=await b(u,a);L(e.hits),a*h>=n?f("We're sorry, but you've reached the end of search results."):v(),O()}catch(e){p(e.message||"Something went wrong, try again later.")}finally{S()}}
//# sourceMappingURL=index.js.map
